version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: TIENDA_CSP
    volumes:
      - ./postgres:/var/lib/postgresql/data
volumes:
  postgres:

