version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: TIENDA_CSP
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pg:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:${PGADMIN_LISTEN_PORT}
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: corbos1995@gmail.com
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin-data:
